FROM nginx:alpine

COPY tools-ui/index.html /usr/share/nginx/html/index.html
COPY tools-ui/widget.js /usr/share/nginx/html/widget.js
COPY tools-ui/style.css /usr/share/nginx/html/style.css

EXPOSE 8484
